{% set name = "openpmd-api" %}
{% set version = "0.8.0a" %}
{% set build = 2 %}
{% set version_fn = version.replace("a", "-alpha") %}
{% set sha256 = "5b2f96850bc65f928b2c250086dd3567e41dbd86686a938c6248155013651ab4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version_fn }}.tar.gz
  url: https://github.com/openPMD/openPMD-api/archive/{{ version_fn }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  skip: True  # [py27]
  run_exports:
    # https://conda.io/docs/user-guide/tasks/build-packages/variants.html#referencing-subpackages
    # in 0.X.*, newer minor versions are compatible
    - {{ pin_subpackage('openpmd-api', min_pin='x.x', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - cmake >=3.11
  host:
    - python
    - pybind11 >=2.2.4
    - adios >=1.13.1  # [unix]
    - hdf5  >=1.8.13
  run:
    - python
    - numpy >=1.15.0
    # FIXME: for some reason warnings about this (ADIOS1 deps)
    - blosc
    - zlib
    - bzip2

test:
  imports:
    - openpmd_api
  commands:
    - python -c "import openpmd_api; print(openpmd_api.__version__);"
    - python -c "import openpmd_api; print(openpmd_api.variants)"
    - test -f ${PREFIX}/lib/cmake/openPMD/openPMDConfig.cmake             # [unix]
    - test -f ${PREFIX}/lib/libopenPMD.so                                 # [linux]
    - otool -L ${PREFIX}/lib/libopenPMD.dylib                             # [osx]
    - if exist %PREFIX%\bin\openPMD.dll (exit 0) else (exit 1)            # [win]
    - otool -L ${PREFIX}/lib/libopenPMD.ADIOS1.Serial.dylib               # [osx]
    - ldd ${PREFIX}/lib/libopenPMD.ADIOS1.Serial.so                       # [linux]
    - if exist %PREFIX%\cmake\openPMDConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.openPMD.org
  license: LGPL 3
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: 'C++ & Python API for writing & reading (.h5, .bp, .json, ...), serial & MPI parallel openPMD files.'

  description: |
    This library provides a common high-level API for openPMD writing and
    reading. It provides a common interface to I/O libraries and file formats
    such as HDF5, ADIOS and JSON.
    Language bindings are provided for C++11 (or newer) and Python 3.
    This conda-forge package only provides serial I/O, please build from source
    for MPI parallel I/O on HPC systems. Window support is limited to HDF5 and
    JSON.
  doc_url: https://openpmd-api.readthedocs.io
  dev_url: https://github.com/openPMD/openPMD-api

extra:
  recipe-maintainers:
    - ax3l
    - C0nsultant
